// <auto-generated />
using System;
using Kolokwium_APBD_s30958.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kolokwium_APBD_s30958.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kolokwium_APBD_s30958.Models.Concert", b =>
                {
                    b.Property<int>("ConcertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConcertId"));

                    b.Property<int>("AvailableTickets")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ConcertId");

                    b.ToTable("Concert");

                    b.HasData(
                        new
                        {
                            ConcertId = 1,
                            AvailableTickets = 0,
                            Date = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Koncert1"
                        },
                        new
                        {
                            ConcertId = 2,
                            AvailableTickets = 0,
                            Date = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Koncert2"
                        });
                });

            modelBuilder.Entity("Kolokwium_APBD_s30958.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            FirstName = "Jan",
                            LastName = "Kowalski",
                            PhoneNumber = ""
                        },
                        new
                        {
                            CustomerId = 2,
                            FirstName = "Kacper",
                            LastName = "Nowak",
                            PhoneNumber = "999-000-999"
                        });
                });

            modelBuilder.Entity("Kolokwium_APBD_s30958.Models.Purchased_Ticket", b =>
                {
                    b.Property<int>("TicketConcertId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TicketConcertId", "CustomerId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Purchased_Ticket");

                    b.HasData(
                        new
                        {
                            TicketConcertId = 1,
                            CustomerId = 1,
                            PurchaseDate = new DateTime(2020, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TicketConcertId = 2,
                            CustomerId = 2,
                            PurchaseDate = new DateTime(2021, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Kolokwium_APBD_s30958.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TicketId");

                    b.ToTable("Ticket");

                    b.HasData(
                        new
                        {
                            TicketId = 1,
                            SeatNumber = 2,
                            SerialNumber = "123456789"
                        },
                        new
                        {
                            TicketId = 2,
                            SeatNumber = 15,
                            SerialNumber = "892324324"
                        });
                });

            modelBuilder.Entity("Kolokwium_APBD_s30958.Models.Ticket_Concert", b =>
                {
                    b.Property<int>("TicketConcertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketConcertId"));

                    b.Property<int>("ConcertId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("TicketConcertId");

                    b.HasIndex("ConcertId");

                    b.HasIndex("TicketId");

                    b.ToTable("Ticket_Concert");

                    b.HasData(
                        new
                        {
                            TicketConcertId = 1,
                            ConcertId = 2,
                            Price = 50m,
                            TicketId = 1
                        },
                        new
                        {
                            TicketConcertId = 2,
                            ConcertId = 1,
                            Price = 75m,
                            TicketId = 2
                        });
                });

            modelBuilder.Entity("Kolokwium_APBD_s30958.Models.Purchased_Ticket", b =>
                {
                    b.HasOne("Kolokwium_APBD_s30958.Models.Customer", "Customer")
                        .WithMany("Purchased_Tickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium_APBD_s30958.Models.Ticket_Concert", "Ticket_Concert")
                        .WithMany("Purchased_Tickets")
                        .HasForeignKey("TicketConcertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Ticket_Concert");
                });

            modelBuilder.Entity("Kolokwium_APBD_s30958.Models.Ticket_Concert", b =>
                {
                    b.HasOne("Kolokwium_APBD_s30958.Models.Concert", "Concert")
                        .WithMany("TicketConcerts")
                        .HasForeignKey("ConcertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium_APBD_s30958.Models.Ticket", "Ticket")
                        .WithMany("TicketConcerts")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concert");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Kolokwium_APBD_s30958.Models.Concert", b =>
                {
                    b.Navigation("TicketConcerts");
                });

            modelBuilder.Entity("Kolokwium_APBD_s30958.Models.Customer", b =>
                {
                    b.Navigation("Purchased_Tickets");
                });

            modelBuilder.Entity("Kolokwium_APBD_s30958.Models.Ticket", b =>
                {
                    b.Navigation("TicketConcerts");
                });

            modelBuilder.Entity("Kolokwium_APBD_s30958.Models.Ticket_Concert", b =>
                {
                    b.Navigation("Purchased_Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
